compilers:
  - name: "gcc"
    version: "7.1"
    skip_packaging: true
    cmake_extra_flags: -DCMAKE_BUILD_TYPE=Debug
  - name: "gcc"
      version: "7.1"
      skip_packaging: true
      cmake_extra_flags: -DCMAKE_BUILD_TYPE=Release