# Enable C++ support
language: cpp
compiler: gcc
# Enable Ubuntu 14.04
dist: trusty

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # Cmake
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ppsspp/cmake
  - sudo apt-get update -qq

install:
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get upgrade -qq

script:
  - mkdir debug-build && cd debug-build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - cd ..
  - mkdir release-build && cd release-build
  - cmake -DCMAKE_BUILD_TYPE=Release .. && make
